### ISSUE TITLE
I'm obviously stupid..

### ISSUE THREAD

**Issue by LordSchtooka** [SteelSeries/gamesense-sdk#10]
I lost my whole afternoon today after buying apex m800 to make audio visualizer to work and I just can't.Could someone do a step-by-step tutorial please ?

**Comment by mbrewerton** [comment]
Hey, if you're still in need of a tutorial, I can help you out, let me know!

**Comment by LordSchtooka** [comment]
yes,id be so grateful

**Comment by mbrewerton** [comment]
Hi, sorry for the late reply, I've been quite busy with work etc. Here's what youi need to do:

1. Download the test.html and audiovisualiser.lsp files and put them in a folder. It doesn't matter where, just so long as they're togtether
2. Open up test.html in Chrome - Note: I tried Edge in Windows 10 and it doesn't work, not sure about old IE.
3. Click the first Browse button and go to this location: **C:\ProgramData\SteelSeries\SteelSeries Engine 3**. If this is hidden on your C:\ drive you can type %programdata% and it will take you to the ProgramData folder.
4. Select the coreProps.json file from the SS Engine folder, this is what lets the application communicate with Engine 3.
5. Now select a music file and enjoy!

Note: I've also found that if you want to test it with a different music file then you need to refresh the page, otherwise it will get confused and do weird things.

**Comment by grikomsn** [comment]
@mbrewerton your five-step tutorial works splendid! Now is it possible to create an audio visualizer for Siberia V3 Prism? Kinda disappointed that the lights on V3 Prism doesn't have the Breathe or audio-based brightness like V3 Frost Blue and such.

**Comment by mbrewerton** [comment]
Really it's possible to create anything with the new Engine 3 and Gamesense. The only two things holding people back is imagination and motivation.

SteelSeries have made Gamesense work in such a way that though it's technical, it's not extremely complicated.

**Comment by dastels** [comment]
@mbrewerton That's one of the best things a person can say about an API/framework.  Thanks.

**Comment by korean6jesus** [comment]
i feel dumb but i can not find the coreProps.json file at all

**Comment by LordSchtooka** [comment]
type %PROGRAMDATA% and search there

**Comment by korean6jesus** [comment]
couldn't find it but thank you

**Comment by ToadKing** [comment]
It should appear at `%PROGRAMDATA%\SteelSeries\SteelSeries Engine 3\coreProps.json`. It will only exists if you have ran SteelSeries Engine 3 at least once.

**Comment by AdamCohan** [comment]
@ToadKing what do you mean "ran it at least once"? Do I need to plug something in or just have the app open. Also please note that I am using a mac, but I doubt that would matter (I know how to locate the file once I can get it to exist on my computer).

**Comment by mbrewerton** [comment]
@AdamCohan As this issue is closed it would be best to raise a new one. But if you open up SS Engine and enable GameSense, the coreprops.json should appear in the Mac directory.
