### ISSUE TITLE
World of Warcraft Gamesense Support

### ISSUE THREAD

**Issue by zeromajstor** [SteelSeries/gamesense-sdk#21]
Hi,

I bought m800 keyboard and I saw that under engine 3 software there are 3 games supported by gamesense. 

It would be good to make support for more popular games like World of Warcraft. WoW is one of the most popular games on the world and new expansion is coming by end of this month. 

Is there chance for you guys to make gamesense work with this keyboard m800? I think there is WoW icon on back of keyboard box :)

I tried to open pull request by it doesn't allow me to open.

**Comment by davidtibbetts** [comment]
Hello zeromajstor,
We would love for World of Warcraft to work with GameSense. Unfortunately it is not up to us entirely. It is up to the game developer, in this case, Blizzard, to add events to their game that are then sent to SteelSeries Engine 3. We have already worked with Valve in order to get CS:GO and Dota 2 supported.
We continue to talk with any and all game developers, big or small, to help them on their end use the gamesense-sdk to send game events to SteelSeries Engine 3 in order to take advantage of the features we provide.
You mentioned a pull request. Do you have something written that sends events from World of Warcraft to SteelSeries Engine 3? If so, we would be more than happy to take a look at your code and help you with any issues you may encounter.
Also a friendly reminder here to always check the latest documentation: https://github.com/SteelSeries/gamesense-sdk/tree/master/doc

Thanks,
-davidtibbetts
