### ISSUE TITLE
Connecting tactile feedback to lisp

### ISSUE THREAD

**Issue by WenkaiHan** [SteelSeries/gamesense-sdk#69]
I'm developing something on Gamesense using javascript/HTML, and I adapted the code here https://www.reddit.com/r/steelseries/comments/5tur1v/gamesense_sdk_is_confusing/ddp88v4?utm_source=share&utm_medium=web2x

I'm wondering what does the

"data": {"value": 1}

mean here in the eventData, and how is it connected to the lisp file?

The following is my lisp code

(handler "TACTILE"
  (lambda (data)
    (let* ((v (value: data)))
      (on-device "vibrate" vibrate: v))))

but right now my mouse only vibrate the first time I run the code, unless I bind the event again every time I call to the event, but this would create a huge latency.

**Comment by JHunz** [comment]
I answered you on reddit, but I'll answer you here as well for posterity:

The value in the data is intended to provide context for the event - Health or ammo 0-100, 0 or 1 for boolean stuff, etc.  The reason it's not vibrating after the first time is that by default an event doesn't re-process when the value sent is the same as the previous.  
  
Since this is great for lighting but not as great for OLEDs and vibration, we later introduced the value_optional flag which you can set when binding your event, which makes it optional to send a value and also makes it re-process the handlers every time even if you do and it is the same.  It's detailed here: https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/sending-game-events.md#registering-an-event

**Comment by WenkaiHan** [comment]
> I answered you on reddit, but I'll answer you here as well for posterity:
> 
> The value in the data is intended to provide context for the event - Health or ammo 0-100, 0 or 1 for boolean stuff, etc. The reason it's not vibrating after the first time is that by default an event doesn't re-process when the value sent is the same as the previous.
> 
> Since this is great for lighting but not as great for OLEDs and vibration, we later introduced the value_optional flag which you can set when binding your event, which makes it optional to send a value and also makes it re-process the handlers every time even if you do and it is the same. It's detailed here: https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/sending-game-events.md#registering-an-event

Thanks so much for the reply! It's really helpful. We're able to resolve the issue with your solution!

**Comment by JHunz** [comment]
Good to hear!
