### ISSUE TITLE
Can´t control device

### ISSUE THREAD

**Issue by leschi** [SteelSeries/gamesense-sdk#70]
Hello,

i want to set the Color of my QCK PRISM mousepad.
I tried it with the following Code:

127.0.0.1:54556/bind_game_event
`{
  "game": "DPD",
  "event": "HEALTH",
  "min_value": 0,
  "max_value": 100,
  "icon_id": 1,
  "handlers": [
    {
      "device-type": "indicator",
      "zone": "two",
      "color": {"gradient": {"zero": {"red": 0, "green": 0, "blue": 255},
                             "hundred": {"red": 0, "green": 255, "blue": 0}}},
      "mode": "percent"
    }
  ]
}`

And then I tried it with:
127.0.0.1:54556/game_event
`{
  "game": "DPD",
  "event": "HEALTH",
  "data": {
      "value": 75
  }
}`

On both requests i get the status 200 but the color wont change.

Do you have any idea, what i do wrong ?
Thanks a lot for your help ;)

**Comment by JHunz** [comment]
The issue is that you're trying to use the "percent" visualization mode with a single zone.  It's designed to be a progressive indication across multiple zones and won't function the way you want it only using one.  You should just use the "color" mode in this case and the color it uses will be calculated from your defined gradient and the value provided.
