### ISSUE TITLE
Send new bitmap every frame for "animation" to OLED devices?

### ISSUE THREAD

**Issue by wolfinabox** [SteelSeries/gamesense-sdk#84]
I'm working on a little animation (dynamic, so can't just be a .gif) for the OLED screen on my Apex 7, and I cannot see from the documentation how/if it's possible to send a new bitmap _per frame_ (as opposed to a single bitmap when binding the event), similar to how you can send different text using the context-frame-key.

The Steelseries app must be able to do this (to show gifs), unless the entire gif is sent to the keyboard at once. Is this possible using the API?

**Comment by JHunz** [comment]
This is something I've been meaning to add to the API for a while but was back-burnered.  Since you're actually asking for it, I've gone ahead and added it internally, and it will be in the next public release of SteelSeries Engine.

The way it will work once released will just be to stick an image-data key in the context frame data, with the same format that you use for the initial handler binding.  If a frame is sent without this key it will show the default image bound in the handler.

**Comment by JHunz** [comment]
Support for this has now shipped in SteelSeries Engine 3.17.9.  Documentation on the final data format can be found in this new section of the documentation: https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/json-handlers-screen.md#sending-dynamic-images-in-event-data
