### ISSUE TITLE
CS:GO gamesense not working under OSX 10.10 and SE 3.4

### ISSUE THREAD

**Issue by Jampo22** [SteelSeries/gamesense-sdk#9]
Hello,
Like the title said, starting the game does not activate the gamesense function.
Also restarting the engine, restarting the game and reloading the cfg does not help.

Any ideas?

Jan

**Comment by samflores23** [comment]
I did some testing on OS X 10.10 with SSE 3.4.2 using the Apex M800 and it works without issues. Are you loading the cfg file manually? Usually SSE 3 loads the config file for you when you launch CS:GO. If you look on the developer console after launching  CS:GO, you should see this:

`Loading GameState Integration: gamestate_integration_steelseries.cgf`

Also, which devices are you using and did you install the latest version of SSE 3?

**Comment by Jampo22** [comment]
Thank you for your awnser!

No it is loaded automaticlly.
Ok I will look it up when Iam back from holiday!

Iam running the latest version and used a Apex. The normal one

Jan

**Comment by Jampo22** [comment]
Iam using a costom cfg and in the console the gamestate_integration_steelseries.cfg is not loaded or listed

**Comment by ToadKing** [comment]
The file should automatically be created when you launch SteelSeries Engine.

Where do you have Steam and CS:GO installed? It could be having issues finding it.

**Comment by Jampo22** [comment]
regular at /Applications/Steam and /Users/jansupper/Library/Application Support/Steam/SteamApps/common/csgo_osx

**Comment by davidtibbetts** [comment]
Where is your SteelSeries Engine 3 installed to?
I suggest deleting the gamestate_integration_steelseries.cfg file you created, to ensure SteelSeries Engine creates the correct one. Then, restart SteelSeries Engine 3 by choosing Quit from the system menu bar's SteelSeries icon and launch the SteelSeries Engine.app again.

Since this is more of a support issue, not an issue with the gamesense-sdk, I am closing this issue. I hope you are able to get it working with the information we have provided, if not, please submit a support ticket so we can better assist you one-on-one.

Thanks,
-Dave

**Comment by PECHViden** [comment]
Does it work for cracked CS:GO? I think it might be work for installing properly from steam. Is there any solution?

**Comment by JHunz** [comment]
Solution: buy the game
